### ISSUE TITLE
Please make your membership of the group public

### ISSUE THREAD

**Issue by kasbah** [OpenKnowHow/okh-identity#1]
If you are happy for people to know you are part of the GitHub organisation please flip your visibility from "private" to "public" on the [members page](https://github.com/orgs/OpenKnowHow/people). That way people that are not part of the group can more easily see that we are more than 3 people. 

@Ceciwantstolearn @jbon @jtc42 @julianstirling @mwweinberg @pciavald @rwb27

**Comment by jtc42** [comment]
Is being private by default a setting we specifically chose? I'm sure that's not the standard behaviour...

**Comment by jbon** [comment]
done

**Comment by kasbah** [comment]
It may be a setting somewhere but I can't find it. In my experience this is the standard Github org behavior.
